### ISSUE TITLE
Missing package cachem

### ISSUE THREAD

**Issue by mnshgl0110** [rfael0cm/RTIGER#5]
RTIGER does not install the dependecy cachem and running it results in the error:
```
Failed with error:  ‘there is no package called ‘cachem’’
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘cachem’
```

**Comment by rfael0cm** [comment]
Hey Manish,
this also has been solved by explaining better how to install it right? I will close it. Let me know if you find the problem.
Best,
Rafa
